name: Node.js CI/CD to VPS

on:
  push:
    branches: ["main", "development", "production"]
  pull_request:
    branches: ["main", "production"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  deploy-dev:
    if: github.ref == 'refs/heads/development'
    needs: build  # chỉ chạy khi build thành công
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up SSH connection for DEV
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts for DEV
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy DEV to VPS and build docker image
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd /root/app/Mysql && git pull && docker compose --env-file .env.dev -f docker-compose.dev.yml up --build -d"
  
  deploy-prod:
    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/main'
    needs: build  # chỉ chạy khi build thành công
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up SSH connection for PROD
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts for PROD
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy PROD to VPS and build docker image
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd /root/app/Mysql && git pull && docker compose --env-file .env.prod -f docker-compose.prod.yml up --build -d"
